title: Daily arXiv Papers - Nickelate Superconductivity
description: Daily fetched arXiv papers on nickelate superconductivity
show_downloads: false

# Kramdown settings
kramdown:
  syntax_highlighter: rouge

# GitHub Pages settings
markdown: kramdown
